# Generated by Django 5.2.16 on 2026-07-22 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_faceimage_user_and_more'),
        ('identity_verification', '0002_alter_identityverificationproof_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField()),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=30)),
                ('embedding_dimension', models.PositiveSmallIntegerField(default=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('LOGIN', 'Login'), ('REAUTH', 'Reauthentication'), ('RESCAN', 'Face Rescan'), ('VERIFY', 'Verification')], default='VERIFY', max_length=20)),
                ('similarity_score', models.FloatField()),
                ('passed', models.BooleanField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liveness_score', models.FloatField()),
                ('liveness_passed', models.BooleanField()),
                ('challenge_sequence', models.JSONField()),
                ('detector_provider', models.CharField(max_length=120)),
                ('detector_version', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
