# Generated by Django 5.2.16 on 2026-07-24 08:57

from django.db import migrations, models


def backfill_evidence_fingerprint(apps, schema_editor):
    IdentityVerificationResult = apps.get_model('identity_verification', 'IdentityVerificationResult')
    for result in IdentityVerificationResult.objects.filter(evidence_fingerprint=''):
        result.evidence_fingerprint = f"legacy-{result.payload_hash}"
        result.save(update_fields=['evidence_fingerprint'])


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0003_faceembedding_faceverificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverificationresult',
            name='evidence_fingerprint',
            field=models.CharField(db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='identityverificationresult',
            name='replay_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_evidence_fingerprint, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='identityverificationresult',
            name='evidence_fingerprint',
            field=models.CharField(db_index=True, default='', max_length=128, unique=True),
        ),
    ]
