# Generated by Django 5.2.16 on 2026-07-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0004_identityverificationresult_evidence_fingerprint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityverificationresult',
            name='evidence_fingerprint',
            field=models.CharField(db_index=True, default='', max_length=128),
        ),
    ]
