# Generated by Django 5.2.16 on 2026-07-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0005_alter_identityverificationresult_evidence_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverificationsession',
            name='recognition_consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
