# Generated by Django 5.2.16 on 2026-08-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity_verification', '0006_identityverificationsession_recognition_consumed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faceembedding',
            options={},
        ),
        migrations.AlterModelOptions(
            name='faceverificationlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='identityverificationproof',
            options={},
        ),
        migrations.AlterModelOptions(
            name='identityverificationresult',
            options={},
        ),
        migrations.AlterModelOptions(
            name='identityverificationsession',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='identityverificationsession',
            name='identity_ve_account_71d739_idx',
        ),
        migrations.AlterModelTable(
            name='devicebiometricpreference',
            table='devicebiometricpreference',
        ),
        migrations.AlterModelTable(
            name='faceembedding',
            table='faceembedding',
        ),
        migrations.AlterModelTable(
            name='faceverificationlog',
            table='faceverificationlog',
        ),
        migrations.AlterModelTable(
            name='identityverificationproof',
            table='identityverificationproof',
        ),
        migrations.AlterModelTable(
            name='identityverificationresult',
            table='identityverificationresult',
        ),
        migrations.AlterModelTable(
            name='identityverificationsession',
            table='identityverificationsession',
        ),
    ]
