# Generated by Django 5.2.16 on 2026-07-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_faceembedding_faceimage_faceverificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_images', to='accounts.account'),
        ),
    ]
