# Generated by Django 5.2.16 on 2026-07-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_faceimage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='faceverificationlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='FaceEmbedding',
        ),
        migrations.DeleteModel(
            name='FaceImage',
        ),
        migrations.DeleteModel(
            name='FaceVerificationLog',
        ),
    ]
