# Generated by Django 5.2.16 on 2026-08-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_faceimage_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totpbackupcode',
            options={},
        ),
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='totpbackupcode',
            table='totpbackupcode',
        ),
        migrations.AlterModelTable(
            name='totpdevice',
            table='totpdevice',
        ),
    ]
