# Generated by Django 5.2.16 on 2026-08-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_totpbackupcode_options_alter_account_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totpbackupcode',
            options={'ordering': ['-created_at']},
        ),
    ]
